"""Copy MiSans unicode-range shards from the npm `misans` package and generate @font-face CSS.

Prepare the package first (version pinned for reproducibility):
  npm pack misans@4.1.0 && tar -xzf misans-4.1.0.tgz

Usage (from repo root):
  .venv/Scripts/python.exe web/scripts/prepare-misans.py <path-to-package/lib/Normal>

Copies MiSans-Regular.*.woff2 / MiSans-Semibold.*.woff2 shards to
web/public/fonts/misans/ and writes web/src/design/misans.css with absolute
/font/misans/ URLs and corrected weights (Regular=400, Semibold=600).
Shards carry unicode-range descriptors, so the browser only downloads the
slices covering rendered text (keeps first-screen font cost small, K3).
"""
import re
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
WEB_ROOT = REPO_ROOT / 'web'
SHARDS_OUT = WEB_ROOT / 'public' / 'fonts' / 'misans'
CSS_OUT = WEB_ROOT / 'src' / 'design' / 'misans.css'

WEIGHTS = {'Regular': 400, 'Semibold': 600}


def main() -> None:
    source_dir = Path(sys.argv[1])
    SHARDS_OUT.mkdir(parents=True, exist_ok=True)
    blocks = []
    for weight_name, weight in WEIGHTS.items():
        css_path = source_dir / f'MiSans-{weight_name}.min.css'
        css = css_path.read_text(encoding='utf-8')
        faces = re.findall(r'@font-face\{[^}]+\}', css)
        for face in faces:
            match = re.search(r"url\('([^']+)'\)", face)
            if not match:
                continue
            shard_name = match.group(1)
            shutil.copy2(source_dir / shard_name, SHARDS_OUT / shard_name)
            face = face.replace(f"url('{shard_name}')", f"url('/fonts/misans/{shard_name}')")
            face = re.sub(r'font-weight:\d+', f'font-weight:{weight}', face)
            blocks.append(face)
        print(f'MiSans-{weight_name}: {len(faces)} faces')
    header = '/* Generated by web/scripts/prepare-misans.py — MiSans unicode-range shards. */\n'
    CSS_OUT.write_text(header + '\n'.join(blocks) + '\n', encoding='utf-8')
    total_kb = sum(file.stat().st_size for file in SHARDS_OUT.glob('*.woff2')) // 1024
    print(f'{CSS_OUT.name}: {len(blocks)} faces, shards on disk {total_kb} KB (lazy-loaded per range)')


if __name__ == '__main__':
    main()